/* ── PALETTE ─────────────────────────────────────────── */
export const palette = [
  '#FF4D4D','#FF7B00','#FFE600','#39FF14','#00F5D4',
  '#4CC9F0','#0066FF','#8B5CF6','#FF0080','#FF69B4',
  '#F72585','#FB5607','#FFCA3A','#8AC926','#06D6A0',
  '#00BFFF','#3A86FF','#9B5DE5','#F15BB5','#FF6B6B',
  '#FFD166','#43AA8B','#118AB2','#EF476F','#26C485',
  '#FF9F1C','#CBFF8C','#00B4D8','#C77DFF','#FF5733',
  '#E63946','#457B9D','#A8DADC','#F1FAEE','#2EC4B6',
  '#E9C46A','#F4A261','#264653','#E76F51','#84A98C',
  '#52B788','#D62828','#023E8A','#48CAE4','#ADE8F4',
  '#CDB4DB','#FFC8DD','#FFAFCC','#BDE0FE','#A2D2FF',
];

/* ── MAKERS ──────────────────────────────────────────── */
export const makers = {
  giripoonati: { name: 'Giri Poonati',    handle: '@giripoonati',  country: 'India',       flag: '🇮🇳', color: '#FF4D4D' },
  aryanm:      { name: 'Aryan Mehta',     handle: '@aryanm',       country: 'India',       flag: '🇮🇳', color: '#FF7B00' },
  sarahkim:    { name: 'Sarah Kim',       handle: '@sarahkim',     country: 'South Korea', flag: '🇰🇷', color: '#4CC9F0' },
  mchen:       { name: 'Marcus Chen',     handle: '@mchen',        country: 'Singapore',   flag: '🇸🇬', color: '#39FF14' },
  priyasharma: { name: 'Priya Sharma',    handle: '@priyasharma',  country: 'India',       flag: '🇮🇳', color: '#8B5CF6' },
  jakew:       { name: 'Jake Wilson',     handle: '@jakew',        country: 'USA',         flag: '🇺🇸', color: '#FFE600' },
  anaro:       { name: 'Ana Rodriguez',   handle: '@anaro',        country: 'Mexico',      flag: '🇲🇽', color: '#06D6A0' },
  tanvir:      { name: 'Tanvir Ahmed',    handle: '@tanvir',       country: 'Bangladesh',  flag: '🇧🇩', color: '#FF0080' },
  liamob:      { name: 'Liam O\'Brien',   handle: '@liamob',       country: 'Ireland',     flag: '🇮🇪', color: '#3A86FF' },
  yukis:       { name: 'Yuki Saito',      handle: '@yukis',        country: 'Japan',       flag: '🇯🇵', color: '#F72585' },
  amirh:       { name: 'Amir Hassan',     handle: '@amirh',        country: 'Egypt',       flag: '🇪🇬', color: '#FB5607' },
  carolined:   { name: 'Caroline Dubois', handle: '@carolined',    country: 'France',      flag: '🇫🇷', color: '#FFCA3A' },
  tomek:       { name: 'Tomasz Kowalski', handle: '@tomek',        country: 'Poland',      flag: '🇵🇱', color: '#E63946' },
  sanjana:     { name: 'Sanjana Rao',     handle: '@sanjana',      country: 'India',       flag: '🇮🇳', color: '#2EC4B6' },
  riku:        { name: 'Riku Mäkinen',    handle: '@riku',         country: 'Finland',     flag: '🇫🇮', color: '#457B9D' },
  omar:        { name: 'Omar Al-Farsi',   handle: '@omar',         country: 'UAE',         flag: '🇦🇪', color: '#F4A261' },
  beatriz:     { name: 'Beatriz Santos',  handle: '@beatriz',      country: 'Brazil',      flag: '🇧🇷', color: '#52B788' },
  nate:        { name: 'Nate Thompson',   handle: '@nate',         country: 'Canada',      flag: '🇨🇦', color: '#9B5DE5' },
};

/* ── PRODUCTS ────────────────────────────────────────── */
export const products = [
  /* Giri */
  { name: 'RefAgent',              category: 'TOOL',          tagline: 'AI research agent for faster knowledge retrieval',              status: 'building', maker: 'giripoonati', mrr: '—',     users: '—',    growth: '—',    desc: 'An AI-powered tool that helps you research faster — pull references, summarise sources, and synthesise knowledge without switching tabs.', links: [{ label: 'Website', type: 'LIVE', url: '#' }], extra: [{ label: 'Stack', value: 'React · OpenAI' }, { label: 'Pricing', value: 'Free' }, { label: 'Platform', value: 'Web' }, { label: 'Since', value: '2024' }] },
  { name: 'CoDrafter',             category: 'SAAS',          tagline: 'Collaborative drafting from first word to final version',       status: 'beta',     maker: 'giripoonati', mrr: '—',     users: '142',  growth: '—',    desc: 'A structured writing environment for teams — draft, comment, version and publish without the chaos of shared docs.', links: [{ label: 'Website', type: 'LIVE', url: '#' }], extra: [{ label: 'Stack', value: 'Next.js · Supabase' }, { label: 'Pricing', value: 'Freemium' }, { label: 'Platform', value: 'Web' }, { label: 'Since', value: '2024' }] },
  { name: 'Shagun Pool',           category: 'WEB APP',       tagline: 'Pool gift money from a group — transparent, zero splits',       status: 'shipped',  maker: 'giripoonati', mrr: '—',     users: '380',  growth: '—',    desc: 'A simple tool for collecting shagun (gift money) from family and friends without the awkward back-and-forth.', links: [{ label: 'Website', type: 'LIVE', url: '#' }], extra: [{ label: 'Stack', value: 'React · Razorpay' }, { label: 'Pricing', value: 'Free' }, { label: 'Platform', value: 'Web' }, { label: 'Since', value: '2023' }] },
  { name: 'FreshScan AI',          category: 'MOBILE',        tagline: 'Scan produce with camera — AI rates freshness instantly',        status: 'building', maker: 'giripoonati', mrr: '—',     users: '—',    growth: '—',    desc: 'Point your camera at fruits or vegetables and get an instant freshness score, nutrition info, and a buy or skip recommendation.', links: [{ label: 'Waitlist', type: 'COMING SOON', url: '#' }], extra: [{ label: 'Stack', value: 'React Native · Vision AI' }, { label: 'Pricing', value: 'Free + Premium' }, { label: 'Platform', value: 'iOS · Android' }, { label: 'Since', value: '2024' }] },
  { name: 'peersupport',           category: 'MOBILE',        tagline: 'Anonymous peer support — share, listen, feel less alone',        status: 'building', maker: 'giripoonati', mrr: '—',     users: '—',    growth: '—',    desc: 'A safe, anonymous space for people going through hard times — share what you\'re feeling, get support from real humans.', links: [{ label: 'Waitlist', type: 'COMING SOON', url: '#' }], extra: [{ label: 'Stack', value: 'React Native · Supabase' }, { label: 'Pricing', value: 'Free' }, { label: 'Platform', value: 'iOS · Android' }, { label: 'Since', value: '2024' }] },
  { name: 'Indians International', category: 'WEB APP',       tagline: 'Community for Indians abroad — find your people anywhere',       status: 'building', maker: 'giripoonati', mrr: '—',     users: '—',    growth: '—',    desc: 'A platform connecting Indians living abroad — find local communities, meetups, jobs, and people who get you.', links: [{ label: 'Website', type: 'LIVE', url: '#' }], extra: [{ label: 'Stack', value: 'Next.js · Supabase' }, { label: 'Pricing', value: 'Free' }, { label: 'Platform', value: 'Web' }, { label: 'Since', value: '2025' }] },
  { name: 'InstaPoll',             category: 'SAAS',          tagline: 'Create instant polls — real-time results, zero friction',        status: 'building', maker: 'giripoonati', mrr: '—',     users: '—',    growth: '—',    desc: 'The fastest way to create a poll and share it — results update live, no login required for voters, works anywhere.', links: [{ label: 'Website', type: 'LIVE', url: '#' }], extra: [{ label: 'Stack', value: 'Next.js · Supabase Realtime' }, { label: 'Pricing', value: 'Free · Pro' }, { label: 'Platform', value: 'Web' }, { label: 'Since', value: '2025' }] },

  /* Aryan */
  { name: 'TaskFlow AI',           category: 'SAAS',          tagline: 'Turn Notion pages into structured task lists automatically',     status: 'active',   maker: 'aryanm',      mrr: '$210',  users: '94',   growth: '+12%', desc: 'Paste any Notion page and get a clean, prioritised task list back in seconds. No more manually parsing your own notes.', links: [{ label: 'Website', type: 'LIVE', url: '#' }, { label: 'Product Hunt', type: 'LAUNCH', url: '#' }], extra: [{ label: 'Stack', value: 'Next.js · GPT-4' }, { label: 'Pricing', value: '$9/mo' }, { label: 'Platform', value: 'Web' }, { label: 'Since', value: '2024' }] },
  { name: 'PriceAlert',            category: 'CHROME EXT',    tagline: 'Get notified when any product price drops — on any site',        status: 'shipped',  maker: 'aryanm',      mrr: '$85',   users: '620',  growth: '+5%',  desc: 'A browser extension that tracks prices across any e-commerce site and sends you a notification the moment it drops.', links: [{ label: 'Chrome Store', type: 'INSTALL', url: '#' }], extra: [{ label: 'Stack', value: 'Chrome Extension · Node' }, { label: 'Pricing', value: 'Free' }, { label: 'Platform', value: 'Chrome' }, { label: 'Since', value: '2023' }] },

  /* Sarah */
  { name: 'ColorToken',            category: 'DESIGN SYSTEM', tagline: 'Generate semantic colour tokens from any brand palette',          status: 'shipped',  maker: 'sarahkim',    mrr: '—',     users: '1.2K', growth: '—',    desc: 'Paste a brand hex colour and get a full semantic token set — primary, neutral, semantic — ready for Figma and CSS.', links: [{ label: 'Figma Community', type: 'FREE', url: '#' }, { label: 'GitHub', type: 'OPEN SOURCE', url: '#' }], extra: [{ label: 'Stack', value: 'Figma Plugin' }, { label: 'Pricing', value: 'Free' }, { label: 'Platform', value: 'Figma' }, { label: 'Since', value: '2023' }] },
  { name: 'DesignSync',            category: 'TOOL',          tagline: 'Keep Figma tokens in sync with your codebase automatically',      status: 'beta',     maker: 'sarahkim',    mrr: '$140',  users: '58',   growth: '+20%', desc: 'A CLI tool that pulls design tokens from Figma and pushes them directly into your repo on every commit.', links: [{ label: 'Website', type: 'LIVE', url: '#' }, { label: 'npm', type: 'PACKAGE', url: '#' }], extra: [{ label: 'Stack', value: 'Node · Figma API' }, { label: 'Pricing', value: '$12/mo' }, { label: 'Platform', value: 'CLI · Web' }, { label: 'Since', value: '2024' }] },

  /* Marcus */
  { name: 'DevLog',                category: 'TOOL',          tagline: 'Auto-generate a changelog from your git commits',                 status: 'active',   maker: 'mchen',       mrr: '$320',  users: '210',  growth: '+8%',  desc: 'Connect your GitHub repo and get a clean, human-readable changelog generated automatically from your commit history.', links: [{ label: 'Website', type: 'LIVE', url: '#' }, { label: 'GitHub', type: 'OPEN SOURCE', url: '#' }], extra: [{ label: 'Stack', value: 'Next.js · GitHub API' }, { label: 'Pricing', value: '$7/mo' }, { label: 'Platform', value: 'Web' }, { label: 'Since', value: '2023' }] },
  { name: 'APIforge',              category: 'API',           tagline: 'Mock APIs instantly — no backend needed to build your frontend',   status: 'active',   maker: 'mchen',       mrr: '$480',  users: '340',  growth: '+15%', desc: 'Define your API schema once and get a live mock endpoint in seconds. Ship your frontend without waiting for the backend.', links: [{ label: 'Website', type: 'LIVE', url: '#' }, { label: 'Docs', type: 'DOCS', url: '#' }], extra: [{ label: 'Stack', value: 'Bun · Cloudflare Workers' }, { label: 'Pricing', value: 'Free · $15/mo' }, { label: 'Platform', value: 'API' }, { label: 'Since', value: '2024' }] },

  /* Priya */
  { name: 'LearnPath',             category: 'WEB APP',       tagline: 'Build structured learning paths from any YouTube playlist',       status: 'shipped',  maker: 'priyasharma', mrr: '—',     users: '890',  growth: '—',    desc: 'Paste a YouTube playlist URL and get a structured course with notes, quizzes, and progress tracking — completely free.', links: [{ label: 'Website', type: 'LIVE', url: '#' }], extra: [{ label: 'Stack', value: 'React · Supabase · YouTube API' }, { label: 'Pricing', value: 'Free' }, { label: 'Platform', value: 'Web' }, { label: 'Since', value: '2024' }] },
  { name: 'QuizBase',              category: 'SAAS',          tagline: 'Generate quizzes from any document, PDF, or URL in seconds',       status: 'beta',     maker: 'priyasharma', mrr: '$95',   users: '130',  growth: '+22%', desc: 'Upload any document or paste a URL and get a full quiz generated instantly. Works for teachers, trainers, and self-learners.', links: [{ label: 'Website', type: 'LIVE', url: '#' }, { label: 'Product Hunt', type: 'LAUNCH', url: '#' }], extra: [{ label: 'Stack', value: 'Next.js · OpenAI' }, { label: 'Pricing', value: 'Free · $8/mo' }, { label: 'Platform', value: 'Web' }, { label: 'Since', value: '2024' }] },

  /* Jake */
  { name: 'ShipFast',              category: 'SAAS',          tagline: 'NextJS boilerplate to build and ship your startup in days',        status: 'active',   maker: 'jakew',       mrr: '$4.2K', users: '860',  growth: '+6%',  desc: 'A production-ready Next.js starter kit with auth, billing, email, and SEO baked in. Stop building infrastructure, start shipping.', links: [{ label: 'Website', type: 'LIVE', url: '#' }, { label: 'Docs', type: 'DOCS', url: '#' }], extra: [{ label: 'Stack', value: 'Next.js · Stripe · Resend' }, { label: 'Pricing', value: '$149 one-time' }, { label: 'Platform', value: 'Web' }, { label: 'Since', value: '2023' }] },
  { name: 'LaunchKit',             category: 'TOOL',          tagline: 'Product Hunt launch checklist, templates, and scheduler',          status: 'shipped',  maker: 'jakew',       mrr: '$180',  users: '420',  growth: '+3%',  desc: 'Everything you need for a successful Product Hunt launch — checklist, first comment templates, badge assets, and a scheduled post planner.', links: [{ label: 'Website', type: 'LIVE', url: '#' }], extra: [{ label: 'Stack', value: 'React · Notion API' }, { label: 'Pricing', value: '$19 one-time' }, { label: 'Platform', value: 'Web' }, { label: 'Since', value: '2023' }] },

  /* Ana */
  { name: 'TranslateNow',          category: 'CHROME EXT',    tagline: 'Translate any selected text instantly with a right-click',         status: 'active',   maker: 'anaro',       mrr: '$60',   users: '2.4K', growth: '+4%',  desc: 'Highlight any text on any page, right-click, and get an instant translation with context — no tab switching, no copy-pasting.', links: [{ label: 'Chrome Store', type: 'INSTALL', url: '#' }], extra: [{ label: 'Stack', value: 'Chrome Extension · DeepL API' }, { label: 'Pricing', value: 'Free · $3/mo' }, { label: 'Platform', value: 'Chrome' }, { label: 'Since', value: '2023' }] },
  { name: 'LocaleKit',             category: 'TOOL',          tagline: 'i18n string manager for dev teams — edit, export, sync',           status: 'beta',     maker: 'anaro',       mrr: '$220',  users: '76',   growth: '+18%', desc: 'A translation management tool built for developers — manage all your i18n strings in one place and sync directly to your repo.', links: [{ label: 'Website', type: 'LIVE', url: '#' }, { label: 'GitHub', type: 'OPEN SOURCE', url: '#' }], extra: [{ label: 'Stack', value: 'Next.js · Supabase' }, { label: 'Pricing', value: 'Free · $15/mo' }, { label: 'Platform', value: 'Web · CLI' }, { label: 'Since', value: '2024' }] },

  /* Tanvir */
  { name: 'FormCraft',             category: 'SAAS',          tagline: 'Build beautiful forms with logic — no code, no friction',           status: 'active',   maker: 'tanvir',      mrr: '$540',  users: '310',  growth: '+11%', desc: 'A form builder that actually looks good — conditional logic, multi-step flows, custom domains, and real-time analytics.', links: [{ label: 'Website', type: 'LIVE', url: '#' }, { label: 'Product Hunt', type: 'LAUNCH', url: '#' }], extra: [{ label: 'Stack', value: 'Vue · Supabase' }, { label: 'Pricing', value: 'Free · $12/mo' }, { label: 'Platform', value: 'Web' }, { label: 'Since', value: '2023' }] },
  { name: 'DataPulse',             category: 'DASHBOARD',     tagline: 'Unified analytics dashboard pulling from 12+ sources',             status: 'beta',     maker: 'tanvir',      mrr: '$310',  users: '88',   growth: '+28%', desc: 'Connect Stripe, Plausible, Supabase, and 9 other sources and see all your key metrics in one clean dashboard.', links: [{ label: 'Website', type: 'LIVE', url: '#' }, { label: 'Docs', type: 'DOCS', url: '#' }], extra: [{ label: 'Stack', value: 'React · Node · Multiple APIs' }, { label: 'Pricing', value: '$18/mo' }, { label: 'Platform', value: 'Web' }, { label: 'Since', value: '2024' }] },

  /* Liam */
  { name: 'RepoReview',            category: 'TOOL',          tagline: 'AI code reviewer that learns your team\'s style guide',            status: 'beta',     maker: 'liamob',      mrr: '$420',  users: '165',  growth: '+34%', desc: 'Connect your GitHub repo and get automated code reviews that match your house style — not generic lint rules.', links: [{ label: 'Website', type: 'LIVE', url: '#' }, { label: 'GitHub App', type: 'INSTALL', url: '#' }], extra: [{ label: 'Stack', value: 'Node · OpenAI · GitHub API' }, { label: 'Pricing', value: '$14/mo' }, { label: 'Platform', value: 'GitHub App' }, { label: 'Since', value: '2024' }] },
  { name: 'StandupBot',            category: 'SAAS',          tagline: 'Async standup summaries for distributed teams — no meetings',      status: 'active',   maker: 'liamob',      mrr: '$780',  users: '290',  growth: '+19%', desc: 'Team members post quick updates asynchronously and StandupBot compiles, summarises, and sends a digest each morning.', links: [{ label: 'Website', type: 'LIVE', url: '#' }, { label: 'Slack App', type: 'INSTALL', url: '#' }], extra: [{ label: 'Stack', value: 'Node · Slack API · OpenAI' }, { label: 'Pricing', value: '$6/seat/mo' }, { label: 'Platform', value: 'Slack · Web' }, { label: 'Since', value: '2023' }] },

  /* Yuki */
  { name: 'TypedCSS',              category: 'TOOL',          tagline: 'TypeScript type definitions auto-generated from your CSS modules', status: 'shipped',  maker: 'yukis',       mrr: '—',     users: '3.1K', growth: '—',    desc: 'A CLI that watches your CSS module files and generates matching TypeScript type definitions so your styles are always typed.', links: [{ label: 'npm', type: 'PACKAGE', url: '#' }, { label: 'GitHub', type: 'OPEN SOURCE', url: '#' }], extra: [{ label: 'Stack', value: 'Node · TypeScript' }, { label: 'Pricing', value: 'Free' }, { label: 'Platform', value: 'CLI' }, { label: 'Since', value: '2023' }] },
  { name: 'Kanji Recall',          category: 'MOBILE',        tagline: 'Spaced repetition kanji learning — 2000 kanji in 6 months',        status: 'active',   maker: 'yukis',       mrr: '$1.1K', users: '4.8K', growth: '+9%',  desc: 'A spaced repetition system specifically designed for kanji, with stroke order animations, radical breakdowns, and example sentences.', links: [{ label: 'App Store', type: 'LIVE', url: '#' }, { label: 'Google Play', type: 'LIVE', url: '#' }], extra: [{ label: 'Stack', value: 'Flutter · Supabase' }, { label: 'Pricing', value: 'Free · $4.99/mo' }, { label: 'Platform', value: 'iOS · Android' }, { label: 'Since', value: '2023' }] },

  /* Amir */
  { name: 'InvoiceZen',            category: 'SAAS',          tagline: 'Invoicing for freelancers — create, send, and get paid in minutes', status: 'active',   maker: 'amirh',       mrr: '$2.3K', users: '1.1K', growth: '+14%', desc: 'No-fluff invoicing built for freelancers — clean templates, multi-currency, automated reminders, and Stripe payment links built in.', links: [{ label: 'Website', type: 'LIVE', url: '#' }, { label: 'Product Hunt', type: 'LAUNCH', url: '#' }], extra: [{ label: 'Stack', value: 'Next.js · Stripe · Supabase' }, { label: 'Pricing', value: 'Free · $9/mo' }, { label: 'Platform', value: 'Web' }, { label: 'Since', value: '2023' }] },
  { name: 'ContractKit',           category: 'WEB APP',       tagline: 'Freelance contract templates — legally sound, plain English',       status: 'shipped',  maker: 'amirh',       mrr: '$390',  users: '720',  growth: '+7%',  desc: 'A library of freelance contract templates that are lawyer-reviewed but written in plain English. Fill in the blanks, download, sign.', links: [{ label: 'Website', type: 'LIVE', url: '#' }], extra: [{ label: 'Stack', value: 'React · PDF.js' }, { label: 'Pricing', value: '$29 one-time' }, { label: 'Platform', value: 'Web' }, { label: 'Since', value: '2023' }] },
  { name: 'TimeboxPro',            category: 'MOBILE',        tagline: 'Time blocking calendar that respects your energy levels',           status: 'beta',     maker: 'amirh',       mrr: '$260',  users: '185',  growth: '+21%', desc: 'A time-blocking app that schedules tasks around your natural energy peaks — deep work in the morning, admin in the afternoon.', links: [{ label: 'TestFlight', type: 'BETA', url: '#' }], extra: [{ label: 'Stack', value: 'React Native · Expo' }, { label: 'Pricing', value: '$6.99/mo' }, { label: 'Platform', value: 'iOS' }, { label: 'Since', value: '2024' }] },

  /* Caroline */
  { name: 'CopyLens',              category: 'CHROME EXT',    tagline: 'AI writing coach that lives inside any text field you type in',     status: 'active',   maker: 'carolined',   mrr: '$880',  users: '2.9K', growth: '+17%', desc: 'A browser extension that analyses your writing as you type — tone, clarity, and concision suggestions without leaving the page.', links: [{ label: 'Chrome Store', type: 'INSTALL', url: '#' }, { label: 'Website', type: 'LIVE', url: '#' }], extra: [{ label: 'Stack', value: 'Chrome Extension · Anthropic API' }, { label: 'Pricing', value: 'Free · $7/mo' }, { label: 'Platform', value: 'Chrome' }, { label: 'Since', value: '2024' }] },
  { name: 'BrandVoice',            category: 'SAAS',          tagline: 'Keep your team\'s writing on-brand — style guide enforcement at scale', status: 'beta',  maker: 'carolined',   mrr: '$450',  users: '98',   growth: '+26%', desc: 'Upload your brand style guide and BrandVoice flags off-brand copy across your entire team in real time — Notion, Docs, CMS, anywhere.', links: [{ label: 'Website', type: 'LIVE', url: '#' }], extra: [{ label: 'Stack', value: 'Next.js · OpenAI · Zapier' }, { label: 'Pricing', value: '$19/seat/mo' }, { label: 'Platform', value: 'Web · API' }, { label: 'Since', value: '2024' }] },

  /* Tomasz */
  { name: 'SchemaSnap',            category: 'TOOL',          tagline: 'Visualise your database schema from a connection string in seconds',  status: 'active',   maker: 'tomek',       mrr: '$290',  users: '430',  growth: '+11%', desc: 'Paste a Postgres, MySQL or SQLite connection string and get an interactive schema diagram — foreign keys, indexes, and all.', links: [{ label: 'Website', type: 'LIVE', url: '#' }, { label: 'GitHub', type: 'OPEN SOURCE', url: '#' }], extra: [{ label: 'Stack', value: 'SvelteKit · Node' }, { label: 'Pricing', value: 'Free · $8/mo' }, { label: 'Platform', value: 'Web' }, { label: 'Since', value: '2024' }] },
  { name: 'EnvGuard',              category: 'TOOL',          tagline: 'Validate .env files against a schema before every deploy',             status: 'shipped',  maker: 'tomek',       mrr: '$110',  users: '870',  growth: '+6%',  desc: 'Define your .env schema once and EnvGuard blocks deploys with missing or malformed variables — works with any CI pipeline.', links: [{ label: 'npm', type: 'PACKAGE', url: '#' }, { label: 'GitHub', type: 'OPEN SOURCE', url: '#' }], extra: [{ label: 'Stack', value: 'Node · TypeScript' }, { label: 'Pricing', value: 'Free' }, { label: 'Platform', value: 'CLI' }, { label: 'Since', value: '2023' }] },
  { name: 'CronWatch',             category: 'DASHBOARD',     tagline: 'Visual cron job monitor with alerting and full run history',           status: 'beta',     maker: 'tomek',       mrr: '$380',  users: '145',  growth: '+23%', desc: 'A dashboard that tracks all your scheduled jobs across servers — see run history, duration trends, and get alerted the moment one fails.', links: [{ label: 'Website', type: 'LIVE', url: '#' }, { label: 'Docs', type: 'DOCS', url: '#' }], extra: [{ label: 'Stack', value: 'Next.js · Postgres · Resend' }, { label: 'Pricing', value: '$12/mo' }, { label: 'Platform', value: 'Web' }, { label: 'Since', value: '2024' }] },

  /* Sanjana */
  { name: 'SkillMap',              category: 'WEB APP',       tagline: 'Visual skill gap analysis for your next career move',                  status: 'beta',     maker: 'sanjana',     mrr: '$160',  users: '540',  growth: '+18%', desc: 'Paste a job description and your CV — SkillMap highlights exactly what skills you have, what you\'re missing, and what to learn next.', links: [{ label: 'Website', type: 'LIVE', url: '#' }, { label: 'Product Hunt', type: 'LAUNCH', url: '#' }], extra: [{ label: 'Stack', value: 'Next.js · OpenAI' }, { label: 'Pricing', value: 'Free · $6/mo' }, { label: 'Platform', value: 'Web' }, { label: 'Since', value: '2024' }] },
  { name: 'NoteFlow',              category: 'SAAS',          tagline: 'Turn meeting recordings into structured, searchable notes instantly',   status: 'active',   maker: 'sanjana',     mrr: '$740',  users: '620',  growth: '+16%', desc: 'Upload a meeting recording or paste a transcript and get back action items, decisions, open questions, and a clean summary — ready to share.', links: [{ label: 'Website', type: 'LIVE', url: '#' }, { label: 'Slack App', type: 'INSTALL', url: '#' }], extra: [{ label: 'Stack', value: 'Next.js · Whisper · Claude' }, { label: 'Pricing', value: '$11/mo' }, { label: 'Platform', value: 'Web · Slack' }, { label: 'Since', value: '2023' }] },
  { name: 'FlashForge',            category: 'MOBILE',        tagline: 'Generate a flashcard deck from any text, PDF, or webpage',             status: 'active',   maker: 'sanjana',     mrr: '$520',  users: '3.2K', growth: '+13%', desc: 'Paste text, upload a PDF, or drop a URL — FlashForge turns it into a spaced repetition deck you can study immediately on mobile.', links: [{ label: 'App Store', type: 'LIVE', url: '#' }, { label: 'Google Play', type: 'LIVE', url: '#' }], extra: [{ label: 'Stack', value: 'Flutter · OpenAI' }, { label: 'Pricing', value: 'Free · $4.99/mo' }, { label: 'Platform', value: 'iOS · Android' }, { label: 'Since', value: '2024' }] },

  /* Riku */
  { name: 'EventStream',           category: 'SAAS',          tagline: 'Real-time event analytics dashboard — no SQL, no data team needed',    status: 'beta',     maker: 'riku',        mrr: '$890',  users: '210',  growth: '+29%', desc: 'Drop in one script tag and get a live dashboard of user events — funnel analysis, retention, and session replays without writing a single query.', links: [{ label: 'Website', type: 'LIVE', url: '#' }, { label: 'Docs', type: 'DOCS', url: '#' }], extra: [{ label: 'Stack', value: 'Go · ClickHouse · Next.js' }, { label: 'Pricing', value: '$19/mo' }, { label: 'Platform', value: 'Web' }, { label: 'Since', value: '2024' }] },
  { name: 'PivotAI',               category: 'TOOL',          tagline: 'Ask questions about your spreadsheet in plain English, get answers',    status: 'active',   maker: 'riku',        mrr: '$1.3K', users: '780',  growth: '+21%', desc: 'Connect a Google Sheet or upload a CSV and start asking questions — PivotAI runs the analysis and explains the result in plain language.', links: [{ label: 'Website', type: 'LIVE', url: '#' }, { label: 'Chrome Store', type: 'INSTALL', url: '#' }], extra: [{ label: 'Stack', value: 'Python · OpenAI · Pandas' }, { label: 'Pricing', value: 'Free · $10/mo' }, { label: 'Platform', value: 'Web · Chrome' }, { label: 'Since', value: '2023' }] },
  { name: 'MetricMate',            category: 'SAAS',          tagline: 'Track the one metric that matters — your north star, simplified',       status: 'building', maker: 'riku',        mrr: '—',     users: '—',    growth: '—',    desc: 'Stop drowning in dashboards. MetricMate asks you to pick one north star metric, connects to your data source, and keeps it front and centre.', links: [{ label: 'Waitlist', type: 'COMING SOON', url: '#' }], extra: [{ label: 'Stack', value: 'Next.js · Supabase' }, { label: 'Pricing', value: 'TBD' }, { label: 'Platform', value: 'Web' }, { label: 'Since', value: '2025' }] },

  /* Omar */
  { name: 'TaxStack',              category: 'SAAS',          tagline: 'Multi-country VAT and GST calculator built for SaaS founders',          status: 'active',   maker: 'omar',        mrr: '$1.8K', users: '940',  growth: '+17%', desc: 'Know exactly what tax you owe in every country your customers are in — TaxStack pulls live rates and generates the right invoices automatically.', links: [{ label: 'Website', type: 'LIVE', url: '#' }, { label: 'API', type: 'DOCS', url: '#' }], extra: [{ label: 'Stack', value: 'Node · Stripe Tax API' }, { label: 'Pricing', value: '$29/mo' }, { label: 'Platform', value: 'Web · API' }, { label: 'Since', value: '2023' }] },
  { name: 'EquityCalc',            category: 'WEB APP',       tagline: 'Startup equity dilution simulator — model every funding round',          status: 'shipped',  maker: 'omar',        mrr: '$60',   users: '1.6K', growth: '+4%',  desc: 'Model your cap table through seed, Series A, B, and beyond. See exactly how much each round dilutes founders, employees, and investors.', links: [{ label: 'Website', type: 'LIVE', url: '#' }], extra: [{ label: 'Stack', value: 'React · Recharts' }, { label: 'Pricing', value: '$19 one-time' }, { label: 'Platform', value: 'Web' }, { label: 'Since', value: '2023' }] },
  { name: 'CashFlow',              category: 'SAAS',          tagline: '90-day cash flow forecast for bootstrapped founders',                    status: 'beta',     maker: 'omar',        mrr: '$420',  users: '270',  growth: '+24%', desc: 'Connect your bank, Stripe, or enter manually — CashFlow projects your next 90 days and flags the week you might run out of money before it happens.', links: [{ label: 'Website', type: 'LIVE', url: '#' }], extra: [{ label: 'Stack', value: 'Next.js · Plaid · Stripe' }, { label: 'Pricing', value: '$14/mo' }, { label: 'Platform', value: 'Web' }, { label: 'Since', value: '2024' }] },

  /* Beatriz */
  { name: 'PaletteStudio',         category: 'DESIGN SYSTEM', tagline: 'AI colour palette generator with WCAG contrast checks built in',        status: 'active',   maker: 'beatriz',     mrr: '$310',  users: '2.1K', growth: '+14%', desc: 'Describe the mood, upload a photo, or pick a base colour — PaletteStudio generates a full accessible palette with contrast ratios for every combination.', links: [{ label: 'Website', type: 'LIVE', url: '#' }, { label: 'Figma Plugin', type: 'INSTALL', url: '#' }], extra: [{ label: 'Stack', value: 'SvelteKit · OpenAI' }, { label: 'Pricing', value: 'Free · $6/mo' }, { label: 'Platform', value: 'Web · Figma' }, { label: 'Since', value: '2024' }] },
  { name: 'IconForge',             category: 'TOOL',          tagline: 'Generate a consistent icon set from a single style description',          status: 'beta',     maker: 'beatriz',     mrr: '$180',  users: '390',  growth: '+31%', desc: 'Describe your visual style once — rounded, minimal, filled, duotone — and IconForge generates a matching set of 200+ SVG icons on demand.', links: [{ label: 'Website', type: 'LIVE', url: '#' }], extra: [{ label: 'Stack', value: 'Next.js · Replicate · SVG' }, { label: 'Pricing', value: '$9/mo' }, { label: 'Platform', value: 'Web' }, { label: 'Since', value: '2024' }] },
  { name: 'FrameSnap',             category: 'CHROME EXT',    tagline: 'Beautiful screenshot frames for product demos and social posts',          status: 'shipped',  maker: 'beatriz',     mrr: '$95',   users: '1.8K', growth: '+8%',  desc: 'Capture any part of any page and instantly wrap it in a beautiful browser frame, device mockup, or gradient background — one click, ready to share.', links: [{ label: 'Chrome Store', type: 'INSTALL', url: '#' }], extra: [{ label: 'Stack', value: 'Chrome Extension · Canvas API' }, { label: 'Pricing', value: 'Free · $4/mo' }, { label: 'Platform', value: 'Chrome' }, { label: 'Since', value: '2023' }] },

  /* Nate */
  { name: 'SlackDigest',           category: 'SAAS',          tagline: 'AI-summarised daily digest of your most important Slack messages',       status: 'active',   maker: 'nate',        mrr: '$1.1K', users: '530',  growth: '+22%', desc: 'SlackDigest watches your channels overnight and sends you a smart morning briefing — decisions made, actions needed, things you can skip.', links: [{ label: 'Website', type: 'LIVE', url: '#' }, { label: 'Slack App', type: 'INSTALL', url: '#' }], extra: [{ label: 'Stack', value: 'Node · Slack API · Claude' }, { label: 'Pricing', value: '$8/mo' }, { label: 'Platform', value: 'Slack' }, { label: 'Since', value: '2024' }] },
  { name: 'MeetingCost',           category: 'CHROME EXT',    tagline: 'Real-time meeting cost counter — shows the price as the clock runs',     status: 'shipped',  maker: 'nate',        mrr: '$40',   users: '3.4K', growth: '+5%',  desc: 'Add attendee salaries once, and MeetingCost displays a live running total during every Google Meet or Zoom call. Makes everyone more decisive.', links: [{ label: 'Chrome Store', type: 'INSTALL', url: '#' }], extra: [{ label: 'Stack', value: 'Chrome Extension · React' }, { label: 'Pricing', value: 'Free' }, { label: 'Platform', value: 'Chrome' }, { label: 'Since', value: '2023' }] },
  { name: 'FocusBox',              category: 'MOBILE',        tagline: 'Website blocker with intelligent deep work session scheduling',           status: 'active',   maker: 'nate',        mrr: '$680',  users: '2.2K', growth: '+15%', desc: 'FocusBox learns when you do your best work and automatically blocks distracting sites during those windows — no willpower required.', links: [{ label: 'App Store', type: 'LIVE', url: '#' }, { label: 'Google Play', type: 'LIVE', url: '#' }], extra: [{ label: 'Stack', value: 'Flutter · ML Kit' }, { label: 'Pricing', value: '$5.99/mo' }, { label: 'Platform', value: 'iOS · Android' }, { label: 'Since', value: '2023' }] },

  /* Aryan — additional */
  { name: 'DocSearch',             category: 'SAAS',          tagline: 'Semantic search for your internal docs — finds meaning, not just words', status: 'beta',     maker: 'aryanm',      mrr: '$340',  users: '120',  growth: '+27%', desc: 'Connect Notion, Confluence, or any markdown docs and get a semantic search bar you can embed anywhere — finds answers, not just keyword matches.', links: [{ label: 'Website', type: 'LIVE', url: '#' }, { label: 'Docs', type: 'DOCS', url: '#' }], extra: [{ label: 'Stack', value: 'Next.js · Embeddings · Pinecone' }, { label: 'Pricing', value: '$15/mo' }, { label: 'Platform', value: 'Web · API' }, { label: 'Since', value: '2024' }] },

  /* Marcus — additional */
  { name: 'HostCheck',             category: 'SAAS',          tagline: 'Uptime monitoring with beautiful public status pages, free tier',         status: 'active',   maker: 'mchen',       mrr: '$920',  users: '1.5K', growth: '+18%', desc: 'Monitor every endpoint, get alerted in under 60 seconds when something breaks, and share a live status page your customers can bookmark.', links: [{ label: 'Website', type: 'LIVE', url: '#' }, { label: 'Status Page Demo', type: 'LIVE', url: '#' }], extra: [{ label: 'Stack', value: 'Go · Cloudflare · Next.js' }, { label: 'Pricing', value: 'Free · $9/mo' }, { label: 'Platform', value: 'Web' }, { label: 'Since', value: '2023' }] },

  /* Priya — additional */
  { name: 'SpeedRead',             category: 'MOBILE',        tagline: 'Adaptive speed reading trainer — read 3x faster in 30 days',             status: 'active',   maker: 'priyasharma', mrr: '$430',  users: '6.1K', growth: '+10%', desc: 'A structured speed reading program that adapts to your current pace, trains peripheral vision, and tracks your WPM and comprehension over time.', links: [{ label: 'App Store', type: 'LIVE', url: '#' }], extra: [{ label: 'Stack', value: 'Swift · Core ML' }, { label: 'Pricing', value: '$4.99/mo' }, { label: 'Platform', value: 'iOS' }, { label: 'Since', value: '2023' }] },

  /* Jake — additional */
  { name: 'WaitlistKit',           category: 'TOOL',          tagline: 'Beautiful waitlist pages with viral referral loops built in',             status: 'shipped',  maker: 'jakew',       mrr: '$560',  users: '1.1K', growth: '+9%',  desc: 'A drop-in waitlist widget with referral tracking, position reveal, and email sequences — set up in 10 minutes, your first viral loop in an hour.', links: [{ label: 'Website', type: 'LIVE', url: '#' }, { label: 'Docs', type: 'DOCS', url: '#' }], extra: [{ label: 'Stack', value: 'Next.js · Resend · Supabase' }, { label: 'Pricing', value: '$29/mo' }, { label: 'Platform', value: 'Web · Embed' }, { label: 'Since', value: '2024' }] },

  /* Ana — additional */
  { name: 'i18nCheck',             category: 'TOOL',          tagline: 'Catch missing translation keys in CI before they reach production',       status: 'shipped',  maker: 'anaro',       mrr: '$130',  users: '490',  growth: '+7%',  desc: 'A CI/CD plugin that compares your locale files, flags missing keys, and fails the build before a half-translated UI reaches your users.', links: [{ label: 'GitHub', type: 'OPEN SOURCE', url: '#' }, { label: 'npm', type: 'PACKAGE', url: '#' }], extra: [{ label: 'Stack', value: 'Node · GitHub Actions' }, { label: 'Pricing', value: 'Free' }, { label: 'Platform', value: 'CLI · CI' }, { label: 'Since', value: '2023' }] },

  /* Tanvir — additional */
  { name: 'SurveyFast',            category: 'SAAS',          tagline: 'Beautiful surveys with AI analysis of open text responses',               status: 'beta',     maker: 'tanvir',      mrr: '$480',  users: '230',  growth: '+25%', desc: 'Build a survey in minutes, collect responses, and let AI cluster and summarise the open-ended answers so you get insight, not a wall of text.', links: [{ label: 'Website', type: 'LIVE', url: '#' }], extra: [{ label: 'Stack', value: 'Vue · OpenAI · Supabase' }, { label: 'Pricing', value: 'Free · $14/mo' }, { label: 'Platform', value: 'Web' }, { label: 'Since', value: '2024' }] },

  /* Liam — additional */
  { name: 'PRBot',                 category: 'TOOL',          tagline: 'Auto-generate pull request descriptions from your diff',                  status: 'active',   maker: 'liamob',      mrr: '$340',  users: '600',  growth: '+20%', desc: 'Install the GitHub App and every PR gets a clear, structured description generated from the diff — what changed, why, and how to test it.', links: [{ label: 'GitHub App', type: 'INSTALL', url: '#' }, { label: 'Website', type: 'LIVE', url: '#' }], extra: [{ label: 'Stack', value: 'Node · GitHub API · Claude' }, { label: 'Pricing', value: 'Free · $6/mo' }, { label: 'Platform', value: 'GitHub' }, { label: 'Since', value: '2024' }] },

  /* Yuki — additional */
  { name: 'DocuType',              category: 'TOOL',          tagline: 'Auto-generate TypeScript types from live API responses',                  status: 'beta',     maker: 'yukis',       mrr: '$290',  users: '520',  growth: '+16%', desc: 'Point DocuType at any REST API and it infers TypeScript types from real responses — including edge cases from multiple calls.', links: [{ label: 'npm', type: 'PACKAGE', url: '#' }, { label: 'GitHub', type: 'OPEN SOURCE', url: '#' }], extra: [{ label: 'Stack', value: 'TypeScript · Node' }, { label: 'Pricing', value: 'Free · $5/mo' }, { label: 'Platform', value: 'CLI' }, { label: 'Since', value: '2024' }] },

  /* Amir — additional */
  { name: 'ProposalKit',           category: 'WEB APP',       tagline: 'Beautiful project proposals for freelancers — close deals faster',        status: 'active',   maker: 'amirh',       mrr: '$670',  users: '890',  growth: '+13%', desc: 'Pick a template, fill in project scope, timeline, and pricing — ProposalKit generates a polished proposal your client can sign in one click.', links: [{ label: 'Website', type: 'LIVE', url: '#' }], extra: [{ label: 'Stack', value: 'Next.js · Stripe · PDF' }, { label: 'Pricing', value: '$12/mo' }, { label: 'Platform', value: 'Web' }, { label: 'Since', value: '2023' }] },

  /* Caroline — additional */
  { name: 'Headlines',             category: 'SAAS',          tagline: 'A/B test your email subject lines before you hit send',                   status: 'beta',     maker: 'carolined',   mrr: '$360',  users: '410',  growth: '+19%', desc: 'Write multiple subject line variants, send to a 10% test group, and Headlines automatically picks the winner to send to the rest of your list.', links: [{ label: 'Website', type: 'LIVE', url: '#' }], extra: [{ label: 'Stack', value: 'Next.js · Resend · Supabase' }, { label: 'Pricing', value: '$11/mo' }, { label: 'Platform', value: 'Web' }, { label: 'Since', value: '2024' }] },

  /* Giri — additional */
  { name: 'PagePulse',             category: 'TOOL',          tagline: 'Monitor competitor websites for changes — get notified instantly',         status: 'building', maker: 'giripoonati', mrr: '—',     users: '—',    growth: '—',    desc: 'Watch any webpage for visual or content changes and get a screenshot diff in your inbox the moment something updates.', links: [{ label: 'Waitlist', type: 'COMING SOON', url: '#' }], extra: [{ label: 'Stack', value: 'Puppeteer · Node · Resend' }, { label: 'Pricing', value: 'Free · Pro' }, { label: 'Platform', value: 'Web' }, { label: 'Since', value: '2025' }] },
  { name: 'SheetBot',              category: 'SAAS',          tagline: 'Chat with your Google Sheets data in plain English',                       status: 'beta',     maker: 'giripoonati', mrr: '$120',  users: '280',  growth: '+31%', desc: 'Connect a Google Sheet and start asking questions in plain English — SheetBot writes the formula or query, runs it, and explains the result.', links: [{ label: 'Website', type: 'LIVE', url: '#' }], extra: [{ label: 'Stack', value: 'Next.js · Google Sheets API · OpenAI' }, { label: 'Pricing', value: 'Free · $8/mo' }, { label: 'Platform', value: 'Web' }, { label: 'Since', value: '2025' }] },
];

/* ── LISTING TIERS (paid promotions overlay) ─────── */
export const listingOverrides = {
  'ShipFast':    { tier: 'paid', cells: 4, border: true, borderColor: '#E0B800', fill: true,  fillColor: '#FFFBE0' },
  'FormCraft':   { tier: 'paid', cells: 2, border: true, borderColor: '#FF0080', fill: true,  fillColor: '#FFE8F2' },
  'TaskFlow AI': { tier: 'paid', cells: 2, border: true, borderColor: '#FF7B00', fill: false, fillColor: null },
  'DesignSync':  { tier: 'paid', cells: 1, border: true, borderColor: '#4CC9F0', fill: false, fillColor: null },
};

// Apply overrides to products array
products.forEach(p => {
  p.listing = listingOverrides[p.name] || { tier: 'free', cells: 1, border: false, fill: false, borderColor: null, fillColor: null };
});

/* ── LAUNCH ORDER (deterministic for Feed view) ─────── */
export const launchOrderByName = [
  'SheetBot', 'PagePulse', 'MetricMate', 'Headlines', 'ProposalKit',
  'DocuType', 'PRBot', 'SurveyFast', 'i18nCheck', 'WaitlistKit',
  'SpeedRead', 'HostCheck', 'DocSearch', 'FocusBox', 'MeetingCost',
  'SlackDigest', 'FrameSnap', 'IconForge', 'PaletteStudio', 'CashFlow',
  'EquityCalc', 'TaxStack', 'FlashForge', 'NoteFlow', 'SkillMap',
  'CronWatch', 'EnvGuard', 'SchemaSnap', 'EventStream', 'PivotAI',
  'InstaPoll', 'Indians International', 'DataPulse', 'FreshScan AI',
  'CoDrafter', 'peersupport', 'QuizBase', 'TaskFlow AI',
  'LocaleKit', 'DesignSync', 'RefAgent', 'APIforge',
  'DevLog', 'FormCraft', 'TranslateNow', 'LearnPath',
  'PriceAlert', 'ColorToken', 'LaunchKit', 'Shagun Pool', 'ShipFast',
  'RepoReview', 'StandupBot', 'TypedCSS', 'Kanji Recall',
  'InvoiceZen', 'ContractKit', 'TimeboxPro', 'CopyLens', 'BrandVoice',
];
