export const tweets = [
  {
    name: 'Jaisal Rathee',
    handle: '@jaisalrathee',
    initials: 'JR',
    color: '#8B5CF6',
    time: '1d',
    text: 'About to hit 90k unique visitors for Tiny Startups 🎉 Almost 90,000 people have visited this little side project. Still can\'t believe it.',
  },
  {
    name: 'Hasan Cagli',
    handle: '@hasancagli',
    initials: 'HC',
    color: '#FF7B00',
    time: '2d',
    text: 'My SaaS just hit $1.6K MRR 🥰 Marketing channels that helped most: SEO + GEO, Reddit posts, and surprisingly cold outreach. No ads.',
  },
  {
    name: 'Evan Yadegari',
    handle: '@evanyadegari',
    initials: 'EY',
    color: '#06D6A0',
    time: '3d',
    text: 'Can\'t believe we hit $1k MRR with @10x_apps. Huge thank you to everyone who signed up and gave feedback. This one felt impossible 3 months ago.',
  },
  {
    name: 'Peer Richelsen',
    handle: '@peer_rich',
    initials: 'PR',
    color: '#FF4D4D',
    time: '3d',
    text: 'Who needs an overhyped AI business when you can simply build a traditional SaaS with +80% margins and a product people actually need.',
  },
  {
    name: 'César Álvarez',
    handle: '@cesaralvarez',
    initials: 'CÁ',
    color: '#4CC9F0',
    time: '4d',
    text: 'My app just hit $450 MRR 🔥 100% organic growth. No ads. Less than 2.5 months since launch. Consistency beats everything.',
  },
  {
    name: 'Damon Chen',
    handle: '@damengchen',
    initials: 'DC',
    color: '#FFE600',
    time: '4d',
    text: '100% inspired by the builders I follow here. Just shipped a screenshots-to-video tool — upload your screenshots, get a demo video in 60s.',
  },
  {
    name: 'Marc Lou',
    handle: '@marc_louvion',
    initials: 'ML',
    color: '#F72585',
    time: '5d',
    text: 'Shipped 10 products in 12 months. Revenue from the ones that stuck: $42k. The ones that failed taught me more than any course ever did.',
  },
  {
    name: 'Pieter Levels',
    handle: '@levelsio',
    initials: 'PL',
    color: '#39FF14',
    time: '5d',
    text: 'The best business model is still: build something useful, charge money for it, keep your costs low. Everything else is noise.',
  },
  {
    name: 'Solt Wagner',
    handle: '@soltwagner',
    initials: 'SW',
    color: '#FF0080',
    time: '6d',
    text: 'Tools to run your business don\'t need to be beautiful on day 1. They need to work. Polish comes after you know people want it.',
  },
  {
    name: 'Lior Neu-ner',
    handle: '@liornn',
    initials: 'LN',
    color: '#FB5607',
    time: '6d',
    text: 'Cold email tip that works: lead with a specific compliment, one line on what you do, one line on why it\'s relevant to them. Under 50 words total.',
  },
  {
    name: 'Danny Postma',
    handle: '@dannypostma',
    initials: 'DP',
    color: '#3A86FF',
    time: '7d',
    text: 'Just crossed $30k MRR across my products. Started with $0 and a lot of doubt. If I can do it anyone reading this can.',
  },
  {
    name: 'Arvid Kahl',
    handle: '@arvidkahl',
    initials: 'AK',
    color: '#FFCA3A',
    time: '7d',
    text: 'Audience before product. Always. It\'s not about having 100k followers. It\'s about having 500 people who trust your recommendations.',
  },
  {
    name: 'Tony Dinh',
    handle: '@tonydinh',
    initials: 'TD',
    color: '#26C485',
    time: '8d',
    text: 'Revenue update: $16k MRR. Slowly but steadily. What helped: stopping to chase viral moments and just focusing on making existing users happy.',
  },
  {
    name: 'Indie Sean',
    handle: '@IndieHackerSean',
    initials: 'IS',
    color: '#C77DFF',
    time: '9d',
    text: 'The unlock for me was realising distribution is a feature. A worse product with better distribution always beats a better product with worse distribution.',
  },
  {
    name: 'Bart',
    handle: '@Baflou',
    initials: 'BF',
    color: '#FF9F1C',
    time: '10d',
    text: 'Looking to sell my product → $50k+ in revenue last 6 months. If you\'re interested in acquiring an indie SaaS DM me.',
  },
];
